#   ____  ___  _     ____   _____     ______  _  ____   __
#  / ___|/ _ \| |   |  _ \ / _ \ \   / / ___|| |/ /\ \ / /
# | |  _| | | | |   | | | | | | \ \ / /\___ \| ' /  \ V / 
# | |_| | |_| | |___| |_| | |_| |\ V /  ___) | . \   | |  
#  \____|\___/|_____|____/ \___/  \_/  |____/|_|\_\  |_|  

# format = """
# [î‚¶](fg:light-black)\
# $custom\
# [î‚°](fg:light-black bg:dark-grey)\
# [î‚°](fg:dark-grey bg:grey)\
# [î‚°](fg:grey bg:light-grey)\
# [î‚°](fg:light-grey bg:black)\
# $os\
# [î‚°](fg:black bg:red)\
# $container\
# [î‚°](fg:red bg:orange)\
# $username\
# [î‚°](fg:orange bg:yellow)\
# $directory\
# [î‚°](fg:yellow bg:green)\
# $git_state$git_status$git_metrics\
# [î‚°](fg:green bg:cyan)\
# [î‚°](fg:cyan bg:blue)\
# [î‚°](fg:blue bg:purple)\
# [î‚°](fg:purple)\
# $fill\
# $cmd_duration\
# $git_branch\
# $line_break\
# $character\
# """

format = """
[î‚¶](fg:light-black)\
[î‚°](fg:light-black bg:dark-grey)\
[î‚°](fg:dark-grey bg:grey)\
[î‚°](fg:grey bg:light-grey)\
[î‚°](fg:light-grey bg:black)\
$os\
[î‚°](fg:black bg:red)\
$container\
[î‚°](fg:red bg:orange)\
$username\
[î‚°](fg:orange bg:yellow)\
$directory\
[î‚°](fg:yellow bg:green)\
$git_state$git_status$git_metrics\
[î‚°](fg:green bg:cyan)\
[î‚°](fg:cyan bg:blue)\
[î‚°](fg:blue bg:purple)\
[î‚°](fg:purple)\
$fill\
$cmd_duration\
[î‚¶](fg:grey)\
$time\
[îƒ–](fg:grey bg:light-black)\
$custom\
[î‚´](fg:light-black)\
$git_branch\
$line_break\
$character\
"""

palette = "custom"

[time]
disabled = false
time_format = "%R"
style = "fg:black bg:grey"
format = '[ïº $time]($style)'

[fill]
symbol = " "

[cmd_duration]
format = "took ~[$duration](bold white)"

[character]
success_symbol = "[â¯](blue bold)[â¯](white bold)[â¯](red bold)"
error_symbol = '[ï€](bold red bold)'

[container]
disabled = false
style = "bg:red fg:white"
format = "[ ïŒˆ ]($style)"

[os]
disabled = false
style = "bg:black fg:white"
format = "[â€‰$symbolâ€‰]($style)"

[os.symbols]
Windows = "ó°²"
Ubuntu = "ó°•ˆ"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "î˜Ÿ"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"

[username]
show_always = true
style_user = "bold bg:orange fg:black"
style_root = "bold bg:orange fg:black"
format = "[ î®™ $user ]($style)"

[directory]
style = "fg:black bg:yellow"
read_only = " î‚¢"
truncation_length = 10
format = '[ ï“” $path$read_only ]($style)'

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "
"Developer" = "ó°²‹ "
"Photography" = "ï€° "
"Memories"= "ó°Ÿ¶ "
"Guitar" = "ó°‹… "

[git_branch]
# round : î‚¶ î‚´
# arrow : îƒ— î‚´
symbol = "ïŠ¬ î¼¹" # î¬€ ï„“ ó°Š¤ ïŠ¬ î„ ó°®  ïŠ– î™œ î… ğŸŒ± ï„¦ î¼¹
# format = "\n [ $symbol $branch ](bold light-grey)"
# chevron light background
# format = "\n [îƒ—](fg:black)[ $symbol ](bold fg:white bg:black)[î‚°](fg:black bg:light-grey)[ $branch ](italic bold fg:black bg:light-grey)[î‚°](fg:light-grey)"
# round empty green
format = "\n [î‚¶](fg:green)[$symbol ](bold fg:black bg:green)[î‚°](fg:green)[ $branch ](italic bold white)"
# round empty dark
# format = "\n [î‚¶](fg:dark-grey)[$symbol ](bold fg:white bg:dark-grey)[î‚°](fg:dark-grey)[ $branch ](italic bold white)"

[git_status]
format = "[$all_status$ahead_behind]($style)"
ahead = " â‡¡$count "
behind = " â‡£$count "
deleted = " ğŸ—‘ï¸$count "
diverged = " âš¡$count "
stashed = " ğŸ“¦$count "
modified = " âœï¸$count "
staged = "âœ”ï¸ $count"
renamed = " ğŸ”„$count "
untracked = " â“$count "
style = "bold fg:black bg:green"

# NOTE : move weather and time into tmux ?
[custom.weather]
command = "~/.config/bash/scripts/weather.sh"
ignore_timeout = true
when = true
style = "fg:white bg:light-black"
format = "[$output]($style)"

# gruvbox
[palettes.custom]
black = "#003b46"
light-black = "#004f5e"
dark-grey = "#006374"
grey = "#007a8a"
light-grey = "#0093a3"
white = "#dce3e8"

red = "#fb4934"            # bright red
green = "#b8bb26"          # bright green
blue = "#83a598"           # tealish blue
yellow = "#fabd2f"         # bright yellow
orange = "#fe8019"         # warm orange
purple = "#d3869b"         # light magenta
cyan = "#8ec07c"           # aquamarine (greenish cyan)

